name: Deploy to Render

on:
  push:
    branches:
      - main  # Yalnız main branch-də dəyişikliklər olduqda işə düşəcək

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Tətbiqinizin tələb etdiyi Node versiyası

      - name: Install dependencies
        run: |
          npm install
        
      - name: Run tests
        run: |
          npm test  # Testlər varsa işləyəcək, yoxdursa bu addımı dəyişdirə bilərsiniz

      - name: Deploy to Render
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}  # Secret istifadə olunur
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK_URL"
